### ISSUE TITLE
TypeError: this.ebb.disconnect is not a function

### ISSUE THREAD

**Issue by MlleDR** [jmpinit/p5.axidraw#2]
_axi.disconnect()_ throws an error when called. I'm using the latest p5.axidraw.js release.

`p5.axidraw.js:2 Uncaught (in promise) TypeError: this.ebb.disconnect is not a function
    at t.<anonymous> (p5.axidraw.js:2:27729)
    at p (p5.axidraw.js:2:19731)
    at Generator.<anonymous> (p5.axidraw.js:2:21086)
    at Generator.next (p5.axidraw.js:2:20094)
    at a (p5.axidraw.js:2:25739)
    at s (p5.axidraw.js:2:25942)
    at p5.axidraw.js:2:26001
    at new Promise (<anonymous>)
    at t.<anonymous> (p5.axidraw.js:2:25882)
    at t.<anonymous> (p5.axidraw.js:2:27835)`

And many thanks for your contribution to p5 community!

**Comment by jmpinit** [comment]
Hello, I'd be happy to help. Could you please share some code & description to illuminate how you are setting things up and getting to the error you shared? It seems like the `AxiDraw` constructor might not have been called?
